services:
  react-app:
    image: frogger155/frontend-app
    ports:
      - "5173:5173"
    networks:
      - app

  django-api:
    image: frogger155/backend
    ports:
      - "8000:8000"
    networks:
      - app

networks:
  app:
    driver: bridge
